export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_SEARCH_VALUE = "UPDATE_SEARCH_VALUE"


export default {
    FETCH_PRODUCTS, FETCH_PRODUCTS_SUCCESS, FETCH_PRODUCTS_FAIL, UPDATE_PRODUCT, UPDATE_SEARCH_VALUE
}